#!/usr/bin/env python
# Note: This script is for testing purposes only
# The executable that is installed by setup.py will be a wrapper script
# that calls checkfort.launcher.main().
import sys
from checkfort import launcher

launcher.main()
sys.exit(0)
